apiVersion: v1
kind: Service
metadata:
  labels:
    application: {{ .Values.labels.application }}
  name: {{ .Values.service.name }}
spec:
  selector:
    application: {{ .Values.selector.matchLabels.type }}
  ports:
  - name: {{ .Values.service.ports.name }}
    port: {{ .Values.service.ports.port }}
    targetPort: {{ .Values.service.ports.targetPort }}
